apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: apb.store.auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apb.store.auth
  template:
    metadata:
      labels:
        app: apb.store.auth
      {{- if .Values.metrics }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
      {{- end }}
    spec:
      containers:
        - name: apb-store-auth
          image: alanbarros/apb.store.auth:{{ .Values.version }}
          ports:
            - containerPort: 80
