apiVersion: v1
kind: Service
metadata:
  name: apbstoreauth-service
spec:
  selector:
    app: apb.store.auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
